added flag experimentalDecorators as required by TS compiler see recent change https://github.com/Microsoft/TypeScript/commit/62ba36908bceed22a52cee3269223189397cbab5#diff-e119cc28df9582f9e1ca0d41720ea142R2025 that adds the error message shown in compiler output:
error TS6064: Option 'experimentalDecorators' must also be specified when option 'emitDecoratorMetadata' is specified.
[18:57:25] TypeScript: 1 global error
[18:57:25] TypeScript: emit succeeded (with errors)